### PR TITLE
Make it work with node v6.0.0

### PR DESCRIPTION
**Pull request by jackhsu978**
I recently upgraded node to v6, but this module is broken after the upgrade. The error message is:

```
TypeError: parsedQuery.hasOwnProperty is not a function
```

To reproduce the problem, try evaluate the following with Node v6:
```
require('url').parse('', true).query.hasOwnProperty('test')
```

It turns out that when query is an empty string, the query object returned from `url.parse` has no method `hasOwnProperty`. This patch fixes the problem.

### CODE REVIEW

**Comment by thoop** [comment]
Looks like no matter what, it evaluates to undefined:
```
url.parse('http://www.example.com?test=true', true).query.hasOwnProperty
```
And it looks like they changed the `querystring` module to call `Object.create(null)` to return an "empty" object instead of `{}`

I don't think `_escaped_fragment_` would ever be on a parent prototype object so I think everything would be ok if we just shortened it to:
```
if(parsedQuery && parsedQuery['_escaped_fragment_']) isRequestingPrerenderedPage = true;
```
What do you think?

**Comment by jackhsu978** [comment]
@thoop yes, I agree. That's actually better!

**Comment by thoop** [comment]
Want to send that in a new pull request and I'll merge it? Thanks for finding that!

**Comment by jackhsu978** [comment]
Just sent another pull request 😄

**Comment by jackhsu978** [comment]
See pull request https://github.com/prerender/prerender-node/pull/104
